import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zero World",
  description: "Generated by Zero World",
  icons: [
    {
      href: "/public/world.png",
      rel: "icon",
      url: "/public/world.png",
    },
    {
      href: "/public/world.png",
      rel: "apple-touch-icon",
      url: "/public/world.png",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientLayout>
          {" "}
          <div suppressHydrationWarning>
            <Toaster />
            {children}
          </div>
        </ClientLayout>
      </body>
    </html>
  );
}
